### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by NiaEevee** [tim-elmer/feminine-female-farmer#3]
I didn't know where to ask about this so I thought I'd open an issue here:
How do I change the config settings for this mod and do I need to download anything else to have it work?

**Comment by tim-elmer** [comment]
You're fine, GitHub is way more visible to me than the NXM forums.

You'll need [SMAPI](https://www.nexusmods.com/stardewvalley/mods/2400) and [Content Patcher](https://www.nexusmods.com/stardewvalley/mods/1915).

Like most SMAPI mods, there is no included config file, you'll need to run the game with the mod installed once to generate it. Once that's done, you'll have a `config.json` file in your mods folder (probably something like `C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\FeminineFemaleFarmer\config.json`). 

In _that_ file, you'll see a series of "keys" and corresponding "values" (e.g., `"Key": "Value"`). Change the desired setting _value_ to one of the options listed in the [Readme](https://github.com/tim-elmer/feminine-female-farmer#readme) and restart the game.

**Comment by NiaEevee** [comment]
It doesn't seem to be generating a config file, is there any way I can manually create it?

**Comment by NiaEevee** [comment]
Do I need to remove the .gitignore file?

**Comment by tim-elmer** [comment]
If you have a `.gitignore`, you probably downloaded the whole source. That'll probably work, but it's generally best practice to download the latest release (e.g., <https://github.com/tim-elmer/feminine-female-farmer/releases/latest>) from GitHub repositories.

As for the `config.json` file not being generated, can you add your console output from SMAPI?

**Comment by NiaEevee** [comment]
I just realized I was launching the program wrong (I was launching Stardew Valley normally instead of using the API).
Now that I'm doing it correctly, it is working.
